// Real admin UI with isolated fixtures: no production requests or Slack messages.
import fs from 'node:fs';import assert from 'node:assert/strict';import {build} from 'esbuild';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE_PATH||'playwright');
const source=await build({entryPoints:['admin/admin.js'],bundle:true,write:false,format:'esm',plugins:[{name:'fixture-client',setup(b){b.onResolve({filter:/^@supabase\/supabase-js$/},()=>({path:'client',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:'export const createClient=()=>window.fakeClient;',loader:'js'}));}}]});
const seed=JSON.parse(fs.readFileSync('../mental/server/supabase/content/initial.json','utf8'));
const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const html=fs.readFileSync('admin/index.html','utf8').replace(/<script[\s\S]*?<\/script>/g,'').replace(/<link[^>]+>/g,'');
 await page.route('http://127.0.0.1:54321/**',r=>r.request().url().endsWith('/assets/app-icon.png')?r.fulfill({contentType:'image/png',body:fs.readFileSync('assets/app-icon.png')}):r.fulfill({contentType:'text/html',body:html}));
 await page.route('https://fixture.supabase.co/**',r=>r.fulfill({contentType:'image/png',body:fs.readFileSync('assets/app-icon.png')}));
 await page.goto('http://127.0.0.1:54321/admin?tab=support&support=00000000-0000-4000-8000-000000000001');await page.addStyleTag({content:fs.readFileSync('admin/admin.css','utf8')});
 await page.evaluate(seed=>{
 window.fetch=async()=>new Response(JSON.stringify({url:'https://fixture.invalid',key:'fixture'}));window.session={};window.calls=[];window.signoutListener=()=>{};
 window.rows=Array.from({length:23},(_,i)=>({id:`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`,category:i%2?'이용 문제':'아이디어',subject:i%2?null:i===0?'[테스트 데이터] 채팅 기능 아이디어':`[테스트 데이터] 아이디어 ${i}`,preview:'화면 사용 중 떠오른 의견입니다.',content:i===0?'[검증용 샘플]\n채팅방 정렬 기능이 있으면 좋겠어요.\n<img src=x onerror="window.injected=true">':'[검증용 샘플] 문의 내용입니다.',reply_email:null,nickname:'테스트 사용자',is_guest:false,created_at:'2026-10-03T04:00:00Z',status:'open',notification_state:i===0?'sent':'pending',has_attachment:i===0,attachmentUrl:'https://fixture.supabase.co/storage/v1/object/sign/mental-media/photo.png?token=fixture'}));
 window.fakeClient={auth:{getSession:async()=>({data:{session:window.session}}),onAuthStateChange:f=>window.signoutListener=f,signOut:async()=>{window.session=null;window.signoutListener('SIGNED_OUT');}},functions:{invoke:async(name,options)=>{
 if(name==='admin-content')return{data:{draft:seed,revision:1,published_revision:1,contracts:[],metadata:[]}};
 if(name==='admin-support'){const b=options.body;window.calls.push(b);if(window.defer){return new Promise(resolve=>window.resolveSupport=resolve);}if(window.fail)return{error:{context:{status:403}}};if(b.action==='detail')return{data:{requests:window.rows.filter(r=>r.id===b.id)}};let rows=window.rows.filter(r=>(!b.category||r.category===b.category)&&(!b.query||JSON.stringify(r).includes(b.query)));return{data:{requests:rows.slice((b.page-1)*b.size,b.page*b.size),total:rows.length,page:b.page,size:b.size}};}
 return{error:new Error('unused fixture')};}}};
 },seed);
 await page.addScriptTag({type:'module',content:source.outputFiles[0].text});await page.locator('#support-detail-body').getByText('[검증용 샘플]',{exact:false}).waitFor();
 assert((await page.locator('#support-detail-body').innerText()).includes('<img'));assert.equal(await page.locator('#support-detail-body img').count(),0);assert.equal(await page.evaluate(()=>window.injected),undefined);assert.equal(await page.locator('#support-detail-attachment img').count(),1);assert.equal(await page.evaluate(()=>sessionStorage.getItem('mental:support:target')),null);
 const out=process.env.QA_SCREENSHOT_DIR;if(out){fs.mkdirSync(out,{recursive:true});await page.screenshot({path:out+'/admin-support-detail.png'});}
 await page.locator('#support-detail-close').click();assert.equal(await page.locator('#support-list tbody tr').count(),20);assert.equal(await page.locator('#support-count').innerText(),'총 23건');if(out)await page.screenshot({path:out+'/admin-support-list.png'});
 await page.locator('#support-next').click();await page.waitForFunction(()=>document.querySelector('#support-page').textContent==='2 / 2');assert.equal(await page.locator('#support-list tbody tr').count(),3);
 await page.locator('#support-category').selectOption('아이디어');await page.waitForFunction(()=>document.querySelector('#support-count').textContent==='총 12건');assert.equal(await page.locator('#support-page').innerText(),'1 / 1');
 await page.locator('#support-search').fill('채팅 기능');await page.locator('#support-search-form').evaluate(e=>e.requestSubmit());await page.waitForFunction(()=>document.querySelector('#support-count').textContent==='총 1건');
 await page.locator('#support-search-clear').click();await page.waitForFunction(()=>document.querySelector('#support-count').textContent==='총 23건');await page.locator('#support-size').selectOption('10');await page.waitForFunction(()=>document.querySelector('#support-page').textContent==='1 / 3');assert.equal(await page.locator('#support-list tbody tr').count(),10);
 for(const width of [430,390,360]){await page.setViewportSize({width,height:844});await page.locator('#support-list button').first().click();await page.locator('#support-detail-body').getByText('[검증용 샘플]',{exact:false}).waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert(await page.locator('#support-detail-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth;}));if(width===390&&out)await page.screenshot({path:out+'/admin-support-mobile.png'});await page.locator('#support-detail-close').click();}
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>window.fail=true);await page.locator('#support-refresh').click();await page.locator('#support-status').getByText('문의 조회 권한이 없습니다.').waitFor();assert.equal(await page.locator('#support-list table').count(),0);
 await page.evaluate(()=>{window.fail=false;window.rows=[];});await page.locator('#support-refresh').click();await page.locator('#support-list').getByText('조건에 맞는 문의·아이디어가 없습니다.').waitFor();
 await page.evaluate(()=>window.defer=true);await page.locator('#support-refresh').click();await page.waitForFunction(()=>typeof window.resolveSupport==='function');await page.locator('#logout').click();await page.evaluate(()=>window.resolveSupport({data:{requests:[],total:0}}));assert(await page.locator('#editor').isHidden());assert.equal(await page.locator('#support-list table').count(),0);assert.equal(await page.locator('#support-detail-body').innerText(),'');assert.deepEqual(errors,[]);
 console.log('PASS support admin: deep link, safe text/photo, filters, pagination, empty/error, 360/390/430 widths, logout race');
}finally{await browser.close();}
